// Date: 10/30/2014 12:53:55 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.majorpotato.steampowered.client.rendering.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelAFBox extends ModelBase
{
  //fields
    ModelRenderer MaterialBoxTop;
    ModelRenderer MaterialBoxLid;
    ModelRenderer MaterialBoxBottom;
    ModelRenderer MaterialBoxMiddle;
  
  public ModelAFBox()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      MaterialBoxTop = new ModelRenderer(this, 0, 41);
      MaterialBoxTop.addBox(0F, 0F, 0F, 16, 4, 16);
      MaterialBoxTop.setRotationPoint(-8F, 9F, -8F);
      MaterialBoxTop.setTextureSize(128, 128);
      MaterialBoxTop.mirror = true;
      setRotation(MaterialBoxTop, 0F, 0F, 0F);
      MaterialBoxLid = new ModelRenderer(this, 0, 61);
      MaterialBoxLid.addBox(0F, 0F, 0F, 14, 1, 14);
      MaterialBoxLid.setRotationPoint(-7F, 8F, -7F);
      MaterialBoxLid.setTextureSize(128, 128);
      MaterialBoxLid.mirror = true;
      setRotation(MaterialBoxLid, 0F, 0F, 0F);
      MaterialBoxBottom = new ModelRenderer(this, 0, 0);
      MaterialBoxBottom.addBox(0F, 0F, 0F, 16, 5, 16);
      MaterialBoxBottom.setRotationPoint(-8F, 19F, -8F);
      MaterialBoxBottom.setTextureSize(128, 128);
      MaterialBoxBottom.mirror = true;
      setRotation(MaterialBoxBottom, 0F, 0F, 0F);
      MaterialBoxMiddle = new ModelRenderer(this, 0, 21);
      MaterialBoxMiddle.addBox(0F, 0F, 0F, 14, 6, 14);
      MaterialBoxMiddle.setRotationPoint(-7F, 13F, -7F);
      MaterialBoxMiddle.setTextureSize(128, 128);
      MaterialBoxMiddle.mirror = true;
      setRotation(MaterialBoxMiddle, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(entity, f, f1, f2, f3, f4, f5);
    MaterialBoxTop.render(f5);
    MaterialBoxLid.render(f5);
    MaterialBoxBottom.render(f5);
    MaterialBoxMiddle.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
